### PR TITLE
Replaced ruby sass with node-sass + Improve theme

### PR DESCRIPTION
**Pull request by mikaykun**
Changed dependencie from grunt-contrib-sass to grunt-sass (works with libsass).
Rewirte Grunt task "sass" with usage grunt-sass.
Testet with nodejs 10.16 and changed version information.

### CODE REVIEW

**Comment by marble** [comment]
Ok, will review that soon. What's the background, what's the rationale of removing the Share font? Is Share not part of the TYPO3 identity any more?

**Comment by benjaminkott** [comment]
Share font is not part of the identity anymore and is going to removed everywhere except the logo itself. Thanks for having a look!

**Comment by marble** [comment]
Hi Daniel, 'force-push' wasn't a good idea, I'm afraid. It has rewritten history. What's the correct way to fix this? My intention is to commit MEINWERK as well and then merge that state into master.
<pre>
* b28a6bd - (vor 28 Minuten) Updated generated CSS files - Martin Bless (MEINWERK)
* d3dc01a - (vor 31 Minuten) Update meta tags für 'docsearch' - Martin Bless
* 506c2fa - (vor 32 Minuten) Fix typo in filename - Martin Bless
* 912516d - (vor 33 Minuten) Make 'stealth' navi buttons better detectable - Martin Bless
* 26766c8 - (vor 34 Minuten) Keep .tip admonition green. It is THE green one! - Martin Bless
* 084872f - (vor 10 Stunden) Keep css map files - Martin Bless
* 2263c33 - (vor 22 Stunden) Ensure correct placement of version selector - Benjamin Kott (temp)
*   d03d4b4 - (vor 22 Stunden) Merge branch 'feature/replace-sass-with-libsass' of https://github.com/mikaykun/t3SphinxThemeRtd into pr/123 - Benjamin Kott
|\  
| * 1ed5e89 - (vor 24 Stunden) Fix syntax within Gruntfile.js - Daniel Siepmann
* | a529df9 - (vor 22 Stunden) Do not use unset sass implementation - Benjamin Kott
|/  
* 075551b - (vor 25 Stunden) Enhance styling and include virtual includes for docs.typo3.org - Benjamin Kott
* 5f5124e - (vor 3 Monaten) Provide even easier usage of commond scripts - Daniel Siepmann
* c71d3d0 - (vor 3 Monaten) Remove error that module was not found - Daniel Siepmann
* 7c13ee7 - (vor 3 Monaten) Replaced ruby sass with node-sass - Joshua Schmidtke
| * 17b21f3 - (vor 3 Stunden) Add label to input - Daniel Siepmann (HEAD -> mikaykun-feature/replace-sass-with-libsass)
| * 6ba531a - (vor 3 Stunden) Add label / alt to image - Daniel Siepmann
| * 61e2628 - (vor 3 Stunden) Do not add landmark within landmark - Daniel Siepmann
| * be07a34 - (vor 10 Stunden) Keep css map files - Martin Bless
| * dd82408 - (vor 22 Stunden) Ensure correct placement of version selector - Benjamin Kott
| * 59476c6 - (vor 22 Stunden) Do not use unset sass implementation - Benjamin Kott
| * 9b69c77 - (vor 24 Stunden) Fix syntax within Gruntfile.js - Daniel Siepmann
| * 4765782 - (vor 25 Stunden) Enhance styling and include virtual includes for docs.typo3.org - Benjamin Kott
| * b399ee8 - (vor 3 Monaten) Provide even easier usage of commond scripts - Daniel Siepmann
| * 3363b49 - (vor 3 Monaten) Remove error that module was not found - Daniel Siepmann
| * 31fa6f7 - (vor 3 Monaten) Replaced ruby sass with node-sass - Joshua Schmidtke
| *   28914f3 - (vor 9 Stunden) Merge pull request #129 from TYPO3-Documentation/sypets-patch-1 - Daniel Siepmann
| |\  
|/ /  
| * 7c556e7 - (vor 9 Stunden) Update header in Readme.rst - Sybille Peters
|/  
| * fe135c4 - (vor 3 Tagen) Add meta tags for indexing by docsearch by algolia - Daniel Siepmann (origin/feature/prepare-for-search-indexing)
|/  
*   aa18286 - (vor 7 Monaten) v3.6.16 Merge branch feature/cleanup-frontend-stack - Martin Bless (tag: v3.6.16, origin/master, origin/HEAD, master)
:
</pre>

**Comment by benjaminkott** [comment]
@marble i guess the best solution is to cherry-pick your changes from a detached head - or a new branch. i you are not sure how to do this, you can push your changes to a new branch to this repository and i can apply the changes for you to this branch.

**Pull request merged**
